FORMAT: 1A

# cook-book

Application for cook book
            
## Recipe api [/recipe/{id}]
            
### Get recipe [GET]

+ Parameters

    + id - A path variable that is required for a valid URL

+ Response 200 (application/json)

        {
            "test":"test"
        }
        
        
## Get list of recipes [/recipes]
            
### Get list of recipes [GET]

+ Response 200 (application/json)

        [
        {
            "test":"test"
        },
        {
            "test":"test"
        },
        {
            "test":"test"
        }
        ]